title: Cutlet
author: rosequ
email: tbd
description: >-
  Cutlet is a BSC based token
baseurl: '/cutlet.github.io/cutlet/'
url: ''

# Build settings
defaults:
  - scope:
      path: '' # an empty string here means all files in the project
    values:
      layout: 'default' # this ensures all content renders with layouts/default.html
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-menus
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
